# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(627, 633)
        Form.setWindowOpacity(1.0)
        Form.setAutoFillBackground(True)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 601, 631))
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.OK = QtGui.QPushButton(self.tab)
        self.OK.setGeometry(QtCore.QRect(160, 10, 41, 31))
        self.OK.setObjectName(_fromUtf8("OK"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(-20, 150, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(370, 90, 211, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.SongLabel = QtGui.QLabel(self.tab)
        self.SongLabel.setGeometry(QtCore.QRect(410, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel.setFont(font)
        self.SongLabel.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel.setObjectName(_fromUtf8("SongLabel"))
        self.Before = QtGui.QTextBrowser(self.tab)
        self.Before.setGeometry(QtCore.QRect(320, 180, 256, 381))
        self.Before.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Before.setObjectName(_fromUtf8("Before"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(420, 150, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.SongName = QtGui.QPlainTextEdit(self.tab)
        self.SongName.setGeometry(QtCore.QRect(200, 10, 211, 31))
        self.SongName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SongName.setObjectName(_fromUtf8("SongName"))
        self.After = QtGui.QTextBrowser(self.tab)
        self.After.setGeometry(QtCore.QRect(30, 180, 256, 381))
        self.After.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.After.setObjectName(_fromUtf8("After"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 60, 251, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.After_2 = QtGui.QTextBrowser(self.tab_2)
        self.After_2.setGeometry(QtCore.QRect(20, 160, 256, 381))
        self.After_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.After_2.setObjectName(_fromUtf8("After_2"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(-30, 130, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.SongName_2_1 = QtGui.QPlainTextEdit(self.tab_2)
        self.SongName_2_1.setGeometry(QtCore.QRect(190, 10, 211, 31))
        self.SongName_2_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SongName_2_1.setObjectName(_fromUtf8("SongName_2_1"))
        self.Before_2_1 = QtGui.QTextBrowser(self.tab_2)
        self.Before_2_1.setGeometry(QtCore.QRect(310, 130, 256, 211))
        self.Before_2_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Before_2_1.setObjectName(_fromUtf8("Before_2_1"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(390, 110, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OK_2 = QtGui.QPushButton(self.tab_2)
        self.OK_2.setGeometry(QtCore.QRect(120, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.OK_2.setFont(font)
        self.OK_2.setObjectName(_fromUtf8("OK_2"))
        self.SongLabel_2 = QtGui.QLabel(self.tab_2)
        self.SongLabel_2.setGeometry(QtCore.QRect(400, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_2.setFont(font)
        self.SongLabel_2.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_2.setObjectName(_fromUtf8("SongLabel_2"))
        self.SongLabel_3 = QtGui.QLabel(self.tab_2)
        self.SongLabel_3.setGeometry(QtCore.QRect(400, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_3.setFont(font)
        self.SongLabel_3.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_3.setObjectName(_fromUtf8("SongLabel_3"))
        self.SongName_2_2 = QtGui.QPlainTextEdit(self.tab_2)
        self.SongName_2_2.setGeometry(QtCore.QRect(190, 60, 211, 31))
        self.SongName_2_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SongName_2_2.setObjectName(_fromUtf8("SongName_2_2"))
        self.Before_2_2 = QtGui.QTextBrowser(self.tab_2)
        self.Before_2_2.setGeometry(QtCore.QRect(310, 350, 256, 231))
        self.Before_2_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Before_2_2.setObjectName(_fromUtf8("Before_2_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.After_3 = QtGui.QTextBrowser(self.tab_3)
        self.After_3.setGeometry(QtCore.QRect(20, 260, 256, 331))
        self.After_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.After_3.setObjectName(_fromUtf8("After_3"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(-30, 230, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.SongName_3 = QtGui.QPlainTextEdit(self.tab_3)
        self.SongName_3.setGeometry(QtCore.QRect(190, 10, 211, 31))
        self.SongName_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SongName_3.setObjectName(_fromUtf8("SongName_3"))
        self.Before_3 = QtGui.QTextBrowser(self.tab_3)
        self.Before_3.setGeometry(QtCore.QRect(310, 260, 256, 331))
        self.Before_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Before_3.setObjectName(_fromUtf8("Before_3"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(410, 230, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.OK_3 = QtGui.QPushButton(self.tab_3)
        self.OK_3.setGeometry(QtCore.QRect(150, 10, 41, 31))
        self.OK_3.setObjectName(_fromUtf8("OK_3"))
        self.SongLabel_4 = QtGui.QLabel(self.tab_3)
        self.SongLabel_4.setGeometry(QtCore.QRect(410, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_4.setFont(font)
        self.SongLabel_4.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_4.setObjectName(_fromUtf8("SongLabel_4"))
        self.SongLabel_5 = QtGui.QLabel(self.tab_3)
        self.SongLabel_5.setGeometry(QtCore.QRect(520, 110, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_5.setFont(font)
        self.SongLabel_5.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_5.setObjectName(_fromUtf8("SongLabel_5"))
        self.replace2 = QtGui.QPlainTextEdit(self.tab_3)
        self.replace2.setGeometry(QtCore.QRect(450, 110, 61, 31))
        self.replace2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replace2.setObjectName(_fromUtf8("replace2"))
        self.SongLabel_6 = QtGui.QLabel(self.tab_3)
        self.SongLabel_6.setGeometry(QtCore.QRect(380, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_6.setFont(font)
        self.SongLabel_6.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_6.setObjectName(_fromUtf8("SongLabel_6"))
        self.replacewith2 = QtGui.QPlainTextEdit(self.tab_3)
        self.replacewith2.setGeometry(QtCore.QRect(310, 110, 61, 31))
        self.replacewith2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replacewith2.setObjectName(_fromUtf8("replacewith2"))
        self.SongLabel_7 = QtGui.QLabel(self.tab_3)
        self.SongLabel_7.setGeometry(QtCore.QRect(380, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_7.setFont(font)
        self.SongLabel_7.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_7.setObjectName(_fromUtf8("SongLabel_7"))
        self.SongLabel_8 = QtGui.QLabel(self.tab_3)
        self.SongLabel_8.setGeometry(QtCore.QRect(520, 70, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_8.setFont(font)
        self.SongLabel_8.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_8.setObjectName(_fromUtf8("SongLabel_8"))
        self.replacewith1 = QtGui.QPlainTextEdit(self.tab_3)
        self.replacewith1.setGeometry(QtCore.QRect(310, 70, 61, 31))
        self.replacewith1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replacewith1.setObjectName(_fromUtf8("replacewith1"))
        self.replace1 = QtGui.QPlainTextEdit(self.tab_3)
        self.replace1.setGeometry(QtCore.QRect(450, 70, 61, 31))
        self.replace1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replace1.setObjectName(_fromUtf8("replace1"))
        self.SongLabel_25 = QtGui.QLabel(self.tab_3)
        self.SongLabel_25.setGeometry(QtCore.QRect(380, 150, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_25.setFont(font)
        self.SongLabel_25.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_25.setObjectName(_fromUtf8("SongLabel_25"))
        self.SongLabel_26 = QtGui.QLabel(self.tab_3)
        self.SongLabel_26.setGeometry(QtCore.QRect(520, 150, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_26.setFont(font)
        self.SongLabel_26.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_26.setObjectName(_fromUtf8("SongLabel_26"))
        self.replacewith3 = QtGui.QPlainTextEdit(self.tab_3)
        self.replacewith3.setGeometry(QtCore.QRect(310, 150, 61, 31))
        self.replacewith3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replacewith3.setObjectName(_fromUtf8("replacewith3"))
        self.replace3 = QtGui.QPlainTextEdit(self.tab_3)
        self.replace3.setGeometry(QtCore.QRect(450, 150, 61, 31))
        self.replace3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replace3.setObjectName(_fromUtf8("replace3"))
        self.SongLabel_27 = QtGui.QLabel(self.tab_3)
        self.SongLabel_27.setGeometry(QtCore.QRect(90, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_27.setFont(font)
        self.SongLabel_27.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_27.setObjectName(_fromUtf8("SongLabel_27"))
        self.replace4 = QtGui.QPlainTextEdit(self.tab_3)
        self.replace4.setGeometry(QtCore.QRect(160, 70, 61, 31))
        self.replace4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replace4.setObjectName(_fromUtf8("replace4"))
        self.replacewith6 = QtGui.QPlainTextEdit(self.tab_3)
        self.replacewith6.setGeometry(QtCore.QRect(20, 150, 61, 31))
        self.replacewith6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replacewith6.setObjectName(_fromUtf8("replacewith6"))
        self.SongLabel_28 = QtGui.QLabel(self.tab_3)
        self.SongLabel_28.setGeometry(QtCore.QRect(90, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_28.setFont(font)
        self.SongLabel_28.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_28.setObjectName(_fromUtf8("SongLabel_28"))
        self.SongLabel_29 = QtGui.QLabel(self.tab_3)
        self.SongLabel_29.setGeometry(QtCore.QRect(230, 150, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_29.setFont(font)
        self.SongLabel_29.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_29.setObjectName(_fromUtf8("SongLabel_29"))
        self.SongLabel_30 = QtGui.QLabel(self.tab_3)
        self.SongLabel_30.setGeometry(QtCore.QRect(230, 70, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_30.setFont(font)
        self.SongLabel_30.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_30.setObjectName(_fromUtf8("SongLabel_30"))
        self.SongLabel_31 = QtGui.QLabel(self.tab_3)
        self.SongLabel_31.setGeometry(QtCore.QRect(230, 110, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_31.setFont(font)
        self.SongLabel_31.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_31.setObjectName(_fromUtf8("SongLabel_31"))
        self.replacewith4 = QtGui.QPlainTextEdit(self.tab_3)
        self.replacewith4.setGeometry(QtCore.QRect(20, 70, 61, 31))
        self.replacewith4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replacewith4.setObjectName(_fromUtf8("replacewith4"))
        self.replace6 = QtGui.QPlainTextEdit(self.tab_3)
        self.replace6.setGeometry(QtCore.QRect(160, 150, 61, 31))
        self.replace6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replace6.setObjectName(_fromUtf8("replace6"))
        self.replacewith5 = QtGui.QPlainTextEdit(self.tab_3)
        self.replacewith5.setGeometry(QtCore.QRect(20, 110, 61, 31))
        self.replacewith5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replacewith5.setObjectName(_fromUtf8("replacewith5"))
        self.replace5 = QtGui.QPlainTextEdit(self.tab_3)
        self.replace5.setGeometry(QtCore.QRect(160, 110, 61, 31))
        self.replace5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.replace5.setObjectName(_fromUtf8("replace5"))
        self.SongLabel_32 = QtGui.QLabel(self.tab_3)
        self.SongLabel_32.setGeometry(QtCore.QRect(90, 150, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_32.setFont(font)
        self.SongLabel_32.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_32.setObjectName(_fromUtf8("SongLabel_32"))
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(280, 60, 20, 131))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.word_changer = QtGui.QPushButton(self.tab_3)
        self.word_changer.setGeometry(QtCore.QRect(250, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.word_changer.setFont(font)
        self.word_changer.setObjectName(_fromUtf8("word_changer"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.SongLabel_9 = QtGui.QLabel(self.tab_4)
        self.SongLabel_9.setGeometry(QtCore.QRect(430, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_9.setFont(font)
        self.SongLabel_9.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_9.setObjectName(_fromUtf8("SongLabel_9"))
        self.firstword = QtGui.QPlainTextEdit(self.tab_4)
        self.firstword.setGeometry(QtCore.QRect(360, 50, 61, 31))
        self.firstword.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.firstword.setObjectName(_fromUtf8("firstword"))
        self.SongLabel_10 = QtGui.QLabel(self.tab_4)
        self.SongLabel_10.setGeometry(QtCore.QRect(420, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_10.setFont(font)
        self.SongLabel_10.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_10.setObjectName(_fromUtf8("SongLabel_10"))
        self.spinBox = QtGui.QSpinBox(self.tab_4)
        self.spinBox.setGeometry(QtCore.QRect(370, 100, 51, 31))
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(15)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.comboBox = QtGui.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(350, 150, 69, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.SongLabel_11 = QtGui.QLabel(self.tab_4)
        self.SongLabel_11.setGeometry(QtCore.QRect(480, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SongLabel_11.setFont(font)
        self.SongLabel_11.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.SongLabel_11.setObjectName(_fromUtf8("SongLabel_11"))
        self.OK_4 = QtGui.QPushButton(self.tab_4)
        self.OK_4.setGeometry(QtCore.QRect(420, 230, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OK_4.setFont(font)
        self.OK_4.setObjectName(_fromUtf8("OK_4"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(120, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(33, 80, 138);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.After_4 = QtGui.QTextBrowser(self.tab_4)
        self.After_4.setGeometry(QtCore.QRect(15, 60, 281, 471))
        self.After_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.After_4.setObjectName(_fromUtf8("After_4"))
        self.line_2 = QtGui.QFrame(self.tab_4)
        self.line_2.setGeometry(QtCore.QRect(320, 30, 20, 551))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "SongReWrite", None))
        self.OK.setText(_translate("Form", "אישור", None))
        self.label_4.setText(_translate("Form", "אחרי", None))
        self.checkBox.setText(_translate("Form", " נסה ליצור חריזה", None))
        self.SongLabel.setText(_translate("Form", "שיר:", None))
        self.Before.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_3.setText(_translate("Form", "לפני", None))
        self.checkBox_3.setText(_translate("Form", "החלפת מילים במילים נרדפות", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "שינוי מילים", None))
        self.label_5.setText(_translate("Form", "אחרי", None))
        self.Before_2_1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_6.setText(_translate("Form", "לפני", None))
        self.OK_2.setText(_translate("Form", "אישור", None))
        self.SongLabel_2.setText(_translate("Form", "שיר 1:", None))
        self.SongLabel_3.setText(_translate("Form", "שיר 2:", None))
        self.Before_2_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "מיזוג שירים", None))
        self.label_7.setText(_translate("Form", "אחרי", None))
        self.Before_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_8.setText(_translate("Form", "לפני", None))
        self.OK_3.setText(_translate("Form", "אישור", None))
        self.SongLabel_4.setText(_translate("Form", "שיר:", None))
        self.SongLabel_5.setText(_translate("Form", "החלף:", None))
        self.SongLabel_6.setText(_translate("Form", "במילה:", None))
        self.SongLabel_7.setText(_translate("Form", "במילה:", None))
        self.SongLabel_8.setText(_translate("Form", "החלף:", None))
        self.SongLabel_25.setText(_translate("Form", "במילה:", None))
        self.SongLabel_26.setText(_translate("Form", "החלף:", None))
        self.SongLabel_27.setText(_translate("Form", "במילה:", None))
        self.SongLabel_28.setText(_translate("Form", "במילה:", None))
        self.SongLabel_29.setText(_translate("Form", "החלף:", None))
        self.SongLabel_30.setText(_translate("Form", "החלף:", None))
        self.SongLabel_31.setText(_translate("Form", "החלף:", None))
        self.SongLabel_32.setText(_translate("Form", "במילה:", None))
        self.word_changer.setText(_translate("Form", "החלף מילים", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "החלפת מילים", None))
        self.SongLabel_9.setText(_translate("Form", "מילה ראשונה בשיר:", None))
        self.SongLabel_10.setText(_translate("Form", "אורך משפט ממוצע:", None))
        self.comboBox.setItemText(0, _translate("Form", "ארוך", None))
        self.comboBox.setItemText(1, _translate("Form", "בינוני", None))
        self.comboBox.setItemText(2, _translate("Form", "קצר", None))
        self.SongLabel_11.setText(_translate("Form", "אורך השיר:", None))
        self.OK_4.setText(_translate("Form", "צור שיר", None))
        self.label_9.setText(_translate("Form", "תוצאה", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "צור שיר", None))

